import fs from 'fs';
let h = fs.readFileSync('stratum-product.html', 'utf8');

// 1. License Activation section
h = h.replace(
  '<h4 style="color: white; margin-top: 1rem;">License Activation</h4>\n                            <ol style="list-style: decimal; padding-left: 1.2rem; color: var(--color-gray-300); font-size: 0.9rem;">\n                                <li style="margin-bottom: 0.3rem;">Obtain a key via <code>python generate_license_key.py</code> (format: <code>XXXXX-XXXXX-XXXXX-XXXXX</code>)</li>\n                                <li style="margin-bottom: 0.3rem;">Open License tab, paste key, click Activate</li>\n                                <li style="margin-bottom: 0.3rem;">All features unlock immediately (no restart needed)</li>\n                            </ol>',
  '<h4 style="color: white; margin-top: 1rem;">Getting Started (Trial)</h4>\n                            <ol style="list-style: decimal; padding-left: 1.2rem; color: var(--color-gray-300); font-size: 0.9rem;">\n                                <li style="margin-bottom: 0.3rem;">Launch Stratum \u2014 a <strong>24-hour free trial</strong> starts automatically on first run</li>\n                                <li style="margin-bottom: 0.3rem;">The License tab shows remaining trial time and which features are locked</li>\n                            </ol>\n\n                            <h4 style="color: white; margin-top: 1rem;">License Activation (From Within the App)</h4>\n                            <ol style="list-style: decimal; padding-left: 1.2rem; color: var(--color-gray-300); font-size: 0.9rem;">\n                                <li style="margin-bottom: 0.3rem;">Purchase a license key from Woven Model (key format: <code>XXXXX-XXXXX-XXXXX-XXXXX</code>)</li>\n                                <li style="margin-bottom: 0.3rem;">Open the <strong>License tab</strong> in Stratum</li>\n                                <li style="margin-bottom: 0.3rem;">Paste your license key into the activation field and click <strong>Activate</strong></li>\n                                <li style="margin-bottom: 0.3rem;">All features unlock immediately \u2014 no restart needed</li>\n                            </ol>'
);

// 2. License Key Format -> How to Activate
h = h.replace(
  '<h3 style="margin-top: 1.5rem; margin-bottom: 1rem;">License Key Format</h3>\n                    <pre><code>python generate_license_key.py\n# Output:\n#   1. XXXXX-XXXXX-XXXXX-XXXXX  \u2705\n#   2. XXXXX-XXXXX-XXXXX-XXXXX  \u2705</code></pre>\n                    <p style="color: var(--color-gray-400);">Keys use format <code>XXXXX-XXXXX-XXXXX-XXXXX</code> with a modulo-36 checksum (20 alphanumeric characters). Generated keys pass validation. Contact Woven Model to obtain a license key.</p>',
  '<h3 style="margin-top: 1.5rem; margin-bottom: 1rem;">How to Activate</h3>\n                    <ol style="list-style: decimal; padding-left: 1.2rem; color: var(--color-gray-300); font-size: 0.9rem;">\n                        <li style="margin-bottom: 0.3rem;">Launch Stratum \u2014 the <strong>License tab</strong> opens automatically or is accessible from the tab bar</li>\n                        <li style="margin-bottom: 0.3rem;">If you haven\'t purchased a key yet, start a <strong>24-hour free trial</strong> with one click</li>\n                        <li style="margin-bottom: 0.3rem;">To activate a full license, paste your key (format: <code>XXXXX-XXXXX-XXXXX-XXXXX</code>) into the activation field and click <strong>Activate</strong></li>\n                        <li style="margin-bottom: 0.3rem;">All features unlock immediately \u2014 no app restart required</li>\n                        <li style="margin-bottom: 0.3rem;">Need a key? <a href="https://calendar.app.google/VcNdH476r22az1kj7" target="_blank" rel="noopener noreferrer">Schedule a consultation</a> with Woven Model to purchase a license</li>\n                    </ol>'
);

// 3. Quick Start -> Portable-first
h = h.replace(
  '<h3 style="margin-bottom: 1rem;">System Requirements</h3>\n                    <ul>\n                        <li><strong>OS:</strong> Windows 10 or 11 (64-bit)</li>\n                        <li><strong>Python:</strong> 3.10 or higher</li>\n                        <li><strong>Disk:</strong> 500 MB minimum (more for cached data)</li>\n                        <li><strong>RAM:</strong> 4 GB minimum, 8 GB recommended</li>\n                    </ul>\n\n                    <h3 style="margin-top: 1.5rem; margin-bottom: 1rem;">Quick Start</h3>\n                    <pre><code># Clone or download the repository\ncd stratum\n\n# Install dependencies\npip install PyQt6 PyQt6-Charts pyqtgraph numpy pandas\npip install yfinance scipy reportlab openpyxl cryptography\n\n# Run the application\npython app.py</code></pre>\n\n                    <p style="color: var(--color-gray-400);">On first launch, Stratum prompts for license activation or starts a <strong>24-hour free trial</strong>. It then creates the default profile, data/logs/reports directories, and opens the Dashboard tab ready for use.</p>\n\n                    <h3 style="margin-top: 1.5rem; margin-bottom: 1rem;">Portable Build</h3>\n                    <pre><code>python build_portable.py --portable</code></pre>\n                    <p style="color: var(--color-gray-400);">Outputs <code>dist/Stratum.exe</code> \u2014 a single-file portable executable. No Python installation required.</p>',
  '<h3 style="margin-bottom: 1rem;">Quick Start (Portable \u2014 No Install Needed)</h3>\n                    <p style="color: var(--color-gray-300); font-size: 0.92rem;">\n                        The easiest way to use Stratum is the <strong>portable executable</strong> \u2014 no Python or dependency setup required:\n                    </p>\n                    <ol style="list-style: decimal; padding-left: 1.2rem; color: var(--color-gray-300); font-size: 0.9rem;">\n                        <li style="margin-bottom: 0.3rem;">Download <code>Stratum.exe</code> from the product page or your license delivery email</li>\n                        <li style="margin-bottom: 0.3rem;">Double-click <code>Stratum.exe</code> to launch the application</li>\n                        <li style="margin-bottom: 0.3rem;">On first launch, choose <strong>Start 24-Hour Free Trial</strong> or activate your license key</li>\n                        <li style="margin-bottom: 0.3rem;">Enter stock symbols, set your date range, and click <strong>Run Backtest</strong></li>\n                    </ol>\n\n                    <h3 style="margin-top: 1.5rem; margin-bottom: 1rem;">System Requirements</h3>\n                    <ul>\n                        <li><strong>OS:</strong> Windows 10 or 11 (64-bit)</li>\n                        <li><strong>Disk:</strong> 500 MB minimum (more for cached data)</li>\n                        <li><strong>RAM:</strong> 4 GB minimum, 8 GB recommended</li>\n                    </ul>\n\n                    <h3 style="margin-top: 1.5rem; margin-bottom: 1rem;">Build from Source (Advanced)</h3>\n                    <p style="color: var(--color-gray-400); font-size: 0.9rem;">If you prefer to run from source code instead of the portable build:</p>\n                    <pre><code>pip install -r requirements.txt\npython app.py</code></pre>\n                    <p style="color: var(--color-gray-400); font-size: 0.88rem;">Requires Python 3.10. See <code>README.md</code> for full details.</p>'
);

fs.writeFileSync('stratum-product.html', h, 'utf8');
console.log('Done');
